#### `playbook-b.yml` (PACS Server):  
- hosts: all  
  become: yes  
  tasks:  
    - name: Install SSH server  
      apk:  
        name: openssh-server  
        state: present  
    - name: Add fake flag 2  
      copy:  
        content: "HTB{p1v0t_t0_p4c5_4_w1n}"  
        dest: /root/flag.txt  
    - name: Enable SSH  
      service:  
        name: sshd  
        enabled: yes  
        state: started
        - name: Create vulnerable C code
      copy:
        content: |
          #include <stdio.h>
          #include <stdlib.h>
          #include <unistd.h>

          int main() {
              if (access("/tmp/exploit_trigger", F_OK) == 0) {
                  setuid(0);
                  system("/bin/cat /root/flag.txt");
              } else {
                  printf("Processing DICOM...\\n");
              }
              return 0;
          }
        dest: /usr/bin/vuln_dicom_handler.c

    - name: Compile vulnerable binary
      command: gcc -o /usr/bin/vuln_dicom_handler /usr/bin/vuln_dicom_handler.c
      args:
        creates: /usr/bin/vuln_dicom_handler

    - name: Remove C source file
      file:
        path: /usr/bin/vuln_dicom_handler.c
        state: absent

    - name: Set SUID permissions
      file:
        path: /usr/bin/vuln_dicom_handler
        owner: root
        group: root
        mode: '4755'

    - name: Create crash handler script
      copy:
        content: |
          #!/bin/bash
          touch /tmp/exploit_trigger
          chmod 666 /tmp/exploit_trigger
          /usr/bin/vuln_dicom_handler | tee /var/log/flag_exposed.log
        dest: /usr/bin/expose_flag.sh
        mode: '0755'

