#### `playbook-a.yml` (DICOM Server):  
- hosts: all  
  become: yes  
  tasks:  
    - name: Install vulnerable DCMTK  
      shell: |  
        git clone https://github.com/DCMTK/dcmtk && cd dcmtk  
        git checkout DCMTK-3.6.8  
        ./configure --prefix=/usr --disable-stack-protector  
        make && make install  
    - name: Add fake flag 1  
      copy:  
        content: "HTB{ju5t_4_d1c0m_b0f}"  
        dest: /opt/dicom/flag1.txt  
    - name: Configure DICOM service  
      systemd:  
        name: dicom-server  
        enabled: yes  
        state: restarted
    - name: Verify DCMTK installation
      stat:
        path: /usr/bin/storescp
      register: dcmtk_installed
    - name: Fail if DCMTK missing
      fail:
        msg: "DCMTK installation failed!"
      when: not dcmtk_installed.stat.exists