---
- name: Install dependencies
  apt:
    name:
      - wget
      - unzip
      - python3
      - python3-pip
      - python3-dicom
    state: present
    update_cache: yes

- name: Create Orthanc directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /etc/orthanc
    - /var/lib/orthanc/db
    - /tmp/dicom-files

- name: Copy Orthanc configuration
  template:
    src: orthanc.json.j2
    dest: /etc/orthanc/orthanc.json
    mode: '0644'

- name: Copy DICOM sample files
  copy:
    src: sample-dicom-files/
    dest: /tmp/dicom-files/
    mode: '0644'

- name: Copy import script
  copy:
    src: import-dicom.py
    dest: /etc/orthanc/import-dicom.py
    mode: '0755'

- name: Create users script
  template:
    src: create-users.sh.j2
    dest: /usr/local/sbin/create-users.sh
    mode: '0755'

- name: Run create users script
  command: /usr/local/sbin/create-users.sh
  args:
    creates: /var/lib/orthanc/.users_created

- name: Copy flag addition script
  template:
    src: add-flag-to-dicom.py.j2
    dest: /tmp/add-flag-to-dicom.py
    mode: '0755'

- name: Add flag to DICOM file
  command: python3 /tmp/add-flag-to-dicom.py
  args:
    creates: /var/lib/orthanc/.flag_added

- name: Pull and run Orthanc container
  docker_container:
    name: orthanc
    image: jodogne/orthanc-plugins:1.9.7
    restart_policy: always
    ports:
      - "{{ orthanc_port }}:4242"
      - "{{ orthanc_web_port }}:8042"
    volumes:
      - /etc/orthanc:/etc/orthanc
      - /var/lib/orthanc/db:/var/lib/orthanc/db
    networks:
      - name: dicom_net
        ipv4_address: "{{ orthanc_ip }}"