name: DICOM Protocol Testing
on: [push]

jobs:
  test-dicom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup DCMTK
      - name: Install DCMTK
        run: |
          sudo apt-get update
          sudo apt-get install -y dcmtk
      
      - name: Create config
        run: |
          mkdir -p /tmp/dcmtk
          echo "[TEST_AE]" > /tmp/dcmtk/dcmqrscp.cfg
          echo "HostName = localhost" >> /tmp/dcmtk/dcmqrscp.cfg
          echo "Port = 11112" >> /tmp/dcmtk/dcmqrscp.cfg  # Use non-privileged port
          echo "StorageDir = /tmp/storage" >> /tmp/dcmtk/dcmqrscp.cfg
          echo "AETitle = TEST_AE" >> /tmp/dcmtk/dcmqrscp.cfg  # Required by dcmqrscp
      
      - name: Start DICOM server
        run: |
          mkdir -p /tmp/storage
          # Use storescp instead of dcmqrscp for C-STORE operations
          storescp +sd /tmp/storage --fork -aet TEST_AE -p 11112 -v > /tmp/dcmtk-server.log 2>&1 &
          sleep 2  # Reduced sleep since storescp starts faster
          echo "Server status:"
          ss -tulpn | grep 11112
          echo "Server log:"
          cat /tmp/dcmtk-server.log
          timeout 30 bash -c 'while ! grep "Ready for Presentation Contexts" /tmp/dcmtk-server.log; do sleep 1; done'
        
      # Install Python dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install requirements
        run: |
          python -m pip install scapy boofuzz pytest
      
      # Run tests
      - name: Execute tests
        run: python -m pytest test_dicom.py -v

      # Run server
      - name: Execute server
        run: python fuzzer.py
