name: DICOM Protocol Testing
on: [push]

jobs:
  test-dicom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Setup DCMTK
      - name: Install DCMTK
        run: |
          sudo apt-get update
          sudo apt-get install -y dcmtk
      
      - name: Create config
        run: |
          mkdir -p /tmp/dcmtk
          echo "[TEST_AE]" > /tmp/dcmtk/dcmqrscp.cfg
          echo "HostName = localhost" >> /tmp/dcmtk/dcmqrscp.cfg
          echo "Port = 11112" >> /tmp/dcmtk/dcmqrscp.cfg  # Use non-privileged port
          echo "StorageDir = /tmp/storage" >> /tmp/dcmtk/dcmqrscp.cfg
          echo "AETitle = TEST_AE" >> /tmp/dcmtk/dcmqrscp.cfg  # Required by dcmqrscp
      
      - name: Start DICOM server
        run: |
          mkdir -p /tmp/storage
          # Run on non-privileged port 11112
          dcmqrscp -c /tmp/dcmtk/dcmqrscp.cfg -d --port 11112 > /tmp/dcmtk-server.log 2>&1 &
          # Add initial sleep for server startup
          sleep 5  
          # Extended timeout with better status checks
          timeout 60 bash -c 'while ! nc -z localhost 11112; do sleep 2; echo "Waiting..."; done'
          echo "Server status:"
          ss -tulpn | grep 11112
          echo "Server log:"
          cat /tmp/dcmtk-server.log
        
      # Install Python dependencies
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install requirements
        run: |
          python -m pip install scapy boofuzz pytest
      
      # Run tests
      - name: Execute tests
        run: python -m pytest test_dicom.py -v

      # Run server
      - name: Execute server
        run: python fuzzer.py
